"""Markdown 리포트 → HTML/PDF.

Sprint 4~5 구현 본격화. 본 파일은:
  - render_html(report) : pure-python markdown→HTML (의존성 없음)
  - render_pdf(html)    : weasyprint lazy import, 미설치 시 ImportError
  - 차트 자리는 caption-only placeholder — Plotly 통합은 Sprint 5 에서.
"""
from __future__ import annotations

import logging
import os
import re
from typing import Iterable

from insights.report_generator import Report

log = logging.getLogger("insights.pdf")

USE_MOCK = os.getenv("USE_MOCK", "false").lower() == "true"


# ---------------------------------------------------------------------------
# Mini markdown → HTML (의존성 없음)
# ---------------------------------------------------------------------------
def _md_to_html(md: str) -> str:
    """매우 단순한 변환 — # 제목, **굵게**, - 리스트, 1. 순서, 빈 줄 단락."""
    out: list[str] = []
    in_ul = in_ol = False
    for line in md.splitlines():
        stripped = line.rstrip()
        # 제목
        m = re.match(r"^(#{1,3})\s+(.*)$", stripped)
        if m:
            if in_ul:
                out.append("</ul>"); in_ul = False
            if in_ol:
                out.append("</ol>"); in_ol = False
            level = len(m.group(1))
            text = _inline(m.group(2))
            out.append(f"<h{level}>{text}</h{level}>")
            continue
        # 무순서 리스트
        if stripped.startswith("- "):
            if in_ol:
                out.append("</ol>"); in_ol = False
            if not in_ul:
                out.append("<ul>"); in_ul = True
            out.append(f"<li>{_inline(stripped[2:])}</li>")
            continue
        # 순서 리스트
        m_ol = re.match(r"^(\d+)\.\s+(.*)$", stripped)
        if m_ol:
            if in_ul:
                out.append("</ul>"); in_ul = False
            if not in_ol:
                out.append("<ol>"); in_ol = True
            out.append(f"<li>{_inline(m_ol.group(2))}</li>")
            continue
        # 빈 줄
        if not stripped:
            if in_ul:
                out.append("</ul>"); in_ul = False
            if in_ol:
                out.append("</ol>"); in_ol = False
            continue
        # 단락
        out.append(f"<p>{_inline(stripped)}</p>")
    if in_ul: out.append("</ul>")
    if in_ol: out.append("</ol>")
    return "\n".join(out)


def _inline(text: str) -> str:
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    return text


_PAGE_CSS = """\
@page { size: A4; margin: 22mm 18mm; }
body { font-family: 'Noto Sans KR', sans-serif; color: #141413;
       background: #FAF9F5; line-height: 1.55; font-size: 11pt; }
h1 { color: #141413; border-bottom: 2px solid #D97757; padding-bottom: 6px; }
h2 { color: #141413; margin-top: 20pt; }
h3 { color: #5C5A52; }
strong { color: #141413; }
ul, ol { margin: 0 0 12pt 18pt; }
li { margin-bottom: 4pt; }
code { background: #F2F0E7; padding: 1pt 4pt; border-radius: 3px;
       font-family: 'Menlo', monospace; font-size: 10pt; }
.footer { margin-top: 32pt; padding-top: 8pt; border-top: 1px solid #E8E6DC;
          font-size: 9pt; color: #5C5A52; }
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def render_html(report: Report, *, charts_caption: Iterable[str] = ()) -> str:
    """리포트 → 완전한 standalone HTML."""
    body_html = _md_to_html(report.markdown)
    captions = "".join(
        f"<p class='chart-caption'>📊 {c}</p>" for c in charts_caption
    )
    footer = (
        f"<div class='footer'>MICEMore Insights · audience={report.audience} · "
        f"model={report.model} · generated by ai-gateway</div>"
    )
    return (
        f"<!DOCTYPE html><html><head><meta charset='utf-8'>"
        f"<style>{_PAGE_CSS}</style></head><body>"
        f"{body_html}{captions}{footer}"
        f"</body></html>"
    )


def render_pdf(html: str) -> bytes:
    """HTML → PDF bytes. weasyprint 필요. mock 모드는 빈 PDF 헤더만."""
    if USE_MOCK:
        # 최소 PDF magic bytes — 실제로는 사용 안 함, 검증용
        return b"%PDF-1.4\n%mock\n"
    try:
        from weasyprint import HTML  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "weasyprint 미설치 — Lambda layer 또는 ECR 이미지에 추가 필요"
        ) from exc
    return HTML(string=html).write_pdf()  # type: ignore[no-any-return]
